language: php
php:
    - "7.1"
    - "7.2"
    - "7.3"
    - "7.4snapshot"
env:
    - WITH_PECL_WEAKREF=false
    - WITH_PECL_WEAKREF=true

matrix:
    exclude:
        - php: "7.3"
          env: WITH_PECL_WEAKREF=true
        - php: "7.4snapshot"
          env: WITH_PECL_WEAKREF=true

before-install:
    - composer self-update
# Install composer dependencies,
# Create database, schema and fixtures
install:
    - composer install
    - if [ "$WITH_PECL_WEAKREF" = "true" ]; then pecl install weakref-beta; fi
